In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.optim import lr_scheduler
import numpy as np
import torchvision
from torchvision import datasets, models, transforms
import matplotlib.pyplot as plt
import time
import os
import pandas as pd
from sklearn.model_selection import train_test_split
import shutil
import time
import copy
from PIL import Image
import glob
import cv2


filepath = 'C:/Users/SIRISHA/Desktop/Face-Mask-Detection-and-Authentication-main/maskmodel3_GoogleNet.pth'
model = torch.load(filepath)


class_names = ['with_mask',
 'without_mask'
]



def process_image(image):
    ''' Scales, crops, and normalizes a PIL image for a PyTorch model,
        returns an Numpy array
    '''
    
    # TODO: Process a PIL image for use in a PyTorch model
    #pil_image = Image.open(image)
    pil_image = image
   
    image_transforms = transforms.Compose([
        transforms.Resize(256),
        transforms.CenterCrop(224),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])
    
    img = image_transforms(pil_image)
    return img
    
    


def classify_face(image):
    device = torch.device("cpu")
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    #im_pil = image.fromarray(image)
    #image = np.asarray(im)
    im = Image.fromarray(image)
    image = process_image(im)
    print('image_processed')
    img = image.unsqueeze_(0)
    img = image.float()

    model.eval()
    model.cpu()
    output = model(image)
    print(output,'##############output###########')
    _, predicted = torch.max(output, 1)
    print(predicted.data[0],"predicted")


    classification1 = predicted.data[0]
    index = int(classification1)
    print(class_names[index])
    return class_names[index]


'''
if __name__ == '__main__':
    #map_location=torch.device('cpu')
    image = cv2.imread('C:/Users/SIRISHA/Desktop/Maskthe faceimages/maksssksksss6.png')
    label = classify_face(image)
    print("the label is", label)
    '''

In [5]:
import cv2

ModuleNotFoundError: No module named 'cv2'

In [1]:
import cv2
import os
from keras.models import load_model
import numpy as np
from pygame import mixer
import time
# from lebel import classify_face


mixer.init()
sound = mixer.Sound('C:/Users/SIRISHA/Desktop/FaceMask_detection_alarm.wav')


#face = cv2.CascadeClassifier('/media/preeth/Data/prajna_files/Drowsiness_detection/haar_cascade_files/haarcascade_frontalface_alt.xml')
cap = cv2.VideoCapture(0)
font = cv2.FONT_HERSHEY_COMPLEX_SMALL
score=0
thicc=2
#faces = face.detectMultiScale(gray,minNeighbors=5,scaleFactor=1.1,minSize=(25,25))
while(True):
    ret, frame = cap.read()
    height,width = frame.shape[:2]
    label = classify_face(frame)
    if(label == 'with_mask'):
        print("No Beep")
    else:
        sound.play()
        print("Beep")   
    cv2.putText(frame,str(label),(100,height-20), font, 1,(255,255,255),1,cv2.LINE_AA)
    cv2.imshow('frame',frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

ModuleNotFoundError: No module named 'cv2'

tensor([[-1.0466,  0.7695]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-2.0274,  1.5672]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-2.1569,  1.7291]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.7489,  1.4056]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.7862,  1.4851]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.5060,  1.0976]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.6114,  1.2483]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.4648,  1

tensor([[-0.9450,  0.7063]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.2810,  0.9238]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.9843,  0.6837]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.9261,  0.6301]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.1044,  0.9247]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.1852,  0.8873]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.1147,  0.8625]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.0848,  0

tensor([[-1.1854,  0.9575]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.3529,  1.0209]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.2016,  0.8597]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.2433,  1.0057]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.1259,  0.8780]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.8687,  0.6664]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-0.9808,  0.6257]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.1687,  0

tensor([[-2.9911,  2.5408]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-3.0744,  2.6195]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-3.3914,  2.8320]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-3.5809,  2.9622]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-3.6632,  2.9937]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-3.4814,  2.8765]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-3.2051,  2.6585]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-3.4681,  2

tensor([[-1.9390,  1.6551]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.9048,  1.5195]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.7887,  1.4566]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.4602,  1.1934]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.7234,  1.4496]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.5263,  1.3088]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.3228,  1.0761]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-1.5120,  1

tensor([[-2.2636,  1.7222]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-2.0759,  1.6285]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-2.4201,  1.8509]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-2.4993,  1.9275]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-2.5826,  2.0439]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-2.8409,  2.3894]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-2.5258,  2.0141]], grad_fn=<AddmmBackward>) ##############output###########
tensor(1) predicted
without_mask
Beep
image_processed
tensor([[-2.4092,  1

KeyboardInterrupt: 

In [4]:
import cv2

ModuleNotFoundError: No module named 'cv2'